### ISSUE TITLE
Display Back Matter media types in a human-readable format

### ISSUE THREAD

**Issue by kylelaker** [EasyDynamics/oscal-react-library#111]
As a user involved in the governance, risk, and compliance of systems and components exploring controls, I want the media type of the back matter resources to be displayed in a human readable format when possible.

### Acceptance Criteria

 - Back matter media types have human-readable names for the common types (OSCAL documents, PDFs, HTML document, etc)
 - If the media type doesn't match to something well-known, the exact value from the `media-type` field is displayed
 - If the media type isn't specified, whichever heuristic is used to determine a media type results in a human readable name (such as using the file extension)
 - Product Owner agrees with the list of recognized types.
 
### Implementation Notes

 - Per [the specification](https://pages.nist.gov/OSCAL/reference/latest/complete/json-reference/#/catalog/back-matter/resources/rlinks/media-type), this is supposed to be an IANA registered media type; however, it seems that some things don't comply with this
   - Our [default catalog](https://raw.githubusercontent.com/usnistgov/oscal-content/master/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json) seems to not specify `media-type` for many documents; however we seem to detect many of them as PDFs or "Unknown"
   - Some of the media types, such as `application/oscal.content+json` is not formally registered as an IANA media type

**Comment by brian-easyd** [comment]
Find an (the?) authoritative source for media types and recognize those.
Enumerate the official list of recognized types and associate with human-friendly names. Consider icons (not required)

**Comment by brian-easyd** [comment]
Core list plus OSCAL extensions.

**Comment by kylelaker** [comment]
@brian-easyd We have an awkward issue with this because of the _very_ small number of back matter resources in existing documents that specify a `media-type`. So in most cases, the viewer today falls back to `Unknown` or a guess based off the file extension.

## Determining Media Type

```mermaid
graph TD
    A([Displaying Media Type]) --> B{Is `media-type` present?}
    B -->|Present| C
    B -->|Absent| D[Use file extension to guess media type]
    D --> E{Can media type\n be determine from\nextension}
    E -->|Media Type Found| C[Convert to friendly-name\nusing lookup]
    E -->|Not Found| Fallback([Display 'Unknown Content'])
    C --> Z([Display friendly name for\nmedia-type])
```

## Friendly names for MIME types

The IANA registrations do not necessarily contain a friendly name. This lists how we will represent specific media types and classes of media types in the viewer.

### `image/`
| Name | Display in Viewer |
|-|-|
| `gif` | GIF |
| `heic` | HEIC Image[^1] |
| `jpeg` | JPEC |
| `png` | PNG |
| `tiff` | TIFF |
| `vnd.adobe.photoshop` | Photoshop PSD |
| `svg+xml` | SVG |

Fallback: "Image"

### `application/`

| Name | Display in Viewer |
|-|-|
| `json` | JSON |
| `oscal.content+json` | OSCAL (JSON) |
| `xml`[^2] | XML |
| `oscal.content+xml` | OSCAL (XML) |
| `octet-stream` | Binary data |
| `msword` | Microsoft Word (`.doc`) |
| `application/vnd.openxmlformats-officedocument.wordprocessingml.document` | Microsoft Word (`.docx`) |
| `vnd.ms-powerpoint` | Microsoft PowerPoint (`.ppt`) |
| `vnd.openxmlformats-officedocument.presentationml.presentation` | Microsoft PowerPoint (`.pptx`) |
| `vnd.ms-excel` | Microsoft Excel (`.xls`) |
| `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` | Microsoft Excel (`.xlsx`)
| `pdf` | PDF |
| `pem-certificate-chain` | PEM Chain |
| `pkcs7-signature` | PKCS7 Signature |
| `pgp-signature` | PGP Signature |
| `ogg` | OGG |
| `rtf` | Rich Text (RTF) |

Fallback: "Binary Data"

### `text/`

| Name | Display in Viewer |
|-|-|
| `html` | HTML |
| `xml`[^2] | XML |
| `oscal.content+xml` | OSCAL (XML) |

Fallback: "Text Content"

### `example/`

We will always report as "Unknown Type". Should never appear in real-world documents.

### No special handling for specific types

| Registry | Display in viewer |
|-|-|
| `audio/*` | Audio |
| `font/*` | Font |
| `message/*` | Message |
| `model/*` | Model |
| `video/*` | Video |

[^1]: Using "Image" is intentional; while HEIC is becoming a more common format, many users do not recognize it as an image type
[^2]: XML appears in both `text/` and `application/` but `application/` is recommended. We will display both as "XML" (and the corresponding OSCAL extension) because they are functionally the same to users.

**Comment by brian-easyd** [comment]
@kylelaker first I want to say that I love this level of planning! Overall this is great and very near what I had in mind. I'd like to offer the following feedback:
- In the flos diagram, where `media-type` is present, we then have the question of "Recognized" (Y/N). If Recognized, the rest of your flow is valid. If not recognized, we should simply display "Not Recognized".
- I'd actually like to see all images represented as "Image (GIF)", "Image (JPG)", etc. Typically the user will care more about whether it's an image (yes or no), and won't care about the image format.
- When we get into AR, audio and video are potentially valid media types, and should at least be displayed as "Audio" or "Video" with the type in parens if know -similar to audio above. Some auditors prefer to record interviews (although often the org or individual staff members don't love that), and may take a video of a screen interaction or a social engineering test.

Otherwise, I think this is great for an MVP. I eventually see our tool recognizing output from other tools, like Nessus scanner output. But we can address those down the road.
