### ISSUE TITLE
OSCAL Component Viewer Example URL Resolution Failure

### ISSUE THREAD

**Issue by zclarkEDC** [EasyDynamics/oscal-react-library#125]
Due to updates in https://github.com/GSA/fedramp-automation/pull/137, the default OSCAL Component URL in the Component Viewer no longer loads.

### Steps to Reproduce
Navigate to https://oscal-viewer.msd.easydynamics.com/component-definition
### Expected Behavior
The Component URL will render a component with the OSCAL Viewer

### Actual Behavior
![OSCAL error](https://user-images.githubusercontent.com/70411989/126198482-84b62af5-5e1a-4060-a690-3ebfa308787d.PNG)

**Comment by ohsh6o** [comment]
I liked your stuff enough I followed it, hello @zclarkEDC and company! 👋 I will be putting PRs shortly to the relevant NIST repo where I though you pulled refs from.

In the meantime:

https://raw.githubusercontent.com/GSA/fedramp-automation/master/dist/content/baselines/rev4/json/FedRAMP_rev4_HIGH-baseline_profile.json

If you want I can send a PR to your fork, but will get to NIST shortly (perhaps later today) or you can take it from there. Apologies, the repo was/is cluttered and we wanted to make clear "hey this is an artifact" versus "hey this is source code you edit" (`dist` versus `src` respectively).

**Comment by ohsh6o** [comment]
Oh, my apologies, I thought it was the profile reference in that `component-definition` that was the issue, am I wrong?

**Comment by ohsh6o** [comment]
In short, @tuckerzp, I was saying what I coded up in EasyDynamics/oscal-content#1.

I hope that helps.

**Comment by tuckerzp** [comment]
@mikeisen1 I was wondering if we had decided to provide a quick fix to our example `Component` or if there was another solution? I just wanted to make sure we are on same page as some other issues depend on this one.

**Comment by mikeisen1** [comment]
> @mikeisen1 I was wondering if we had decided to provide a quick fix to our example `Component` or if there was another solution? I just wanted to make sure we are on same page as some other issues depend on this one.

I figured we would wait until the pull request in the `oscal-content` repository is merged, which would resolve this. However, if you want me to tell you how to temporarily fix this issue I can let you know.

**Comment by tuckerzp** [comment]
> temporarily fix this issue

Loading this for now does fix it: https://raw.githubusercontent.com/EasyDynamics/oscal-content/5ef5b3709045ba3aab1473813c13436e886d6185/examples/component-definition/json/example-component.json

> I figured we would wait until the pull request in the `oscal-content` repository is merged

https://github.com/EasyDynamics/oscal-content/pull/1 is still in a draft it seems. Should it be taken out of draft or should we copy what has been done in our own PR? If we take it out of draft, it would be pretty easy for anyone to review.

**Comment by mikeisen1** [comment]
> [EasyDynamics/oscal-content#1](https://github.com/EasyDynamics/oscal-content/pull/1) is still in a draft it seems. Should it be taken out of draft or should we copy what has been done in our own PR? If we take it out of draft, it would be pretty easy for anyone to review.

I think we should take it out of draft, so we can review it (and approve it as long as everything seems to be good to go, which should be the case) and avoid future issues. There's only one line that was changed, so there's not too much to actually review.

**Comment by tuckerzp** [comment]
Closed with https://github.com/EasyDynamics/oscal-content/pull/1
