### ISSUE TITLE
Errors In Example JSON Data

### ISSUE THREAD

**Issue by mikeisen1** [EasyDynamics/oscal-react-library#142]
When using the following example component file,

`https://raw.githubusercontent.com/EasyDynamics/oscal-content/manual-fix-of-component-paths/examples/component-definition/json/example-component-min.json`,

we get the following error:

`Yikes! Something went wrong loading the OSCAL data. Sorry, we'll look into it. (Unexpected token : in JSON at position 3)`.

**Steps to reproduce**
1. Go to component viewer
2. Enter the above component file in the component url box
3. Click on the reload button

**Acceptance Criteria**
- The above error does not occur in the `example-component-min` file or in any of the other example files

**Comment by tuckerzp** [comment]
Error seems to be specifically due to this line having a `404` 

https://github.com/EasyDynamics/oscal-content/blob/58af5c83ad7ab5620809c5701877a4b959516d25/examples/component-definition/json/example-component-min.json#L43

**Comment by rgauss** [comment]
We didn't update the minified versions (`*-min.json`) in any of our temporary workarounds.

These issues are known to NIST and FedRAMP and fixes are planned on their side.
