### ISSUE TITLE
Investigate GitHub Discussions

### ISSUE THREAD

**Issue by tuckerzp** [EasyDynamics/oscal-react-library#153]
As a member of the community, it would be useful to start and participate in discussions for the project outside of the typical issue format. 

I do not know if we have looked into this much before but it could be something to consider. https://docs.github.com/en/discussions/quickstart has documentation on it. This could be a good way to start and maintain discussions on the project with the community.

**Comment by rgauss** [comment]
We had considered adding Gitter for real time communication, but happy to start with GitHub Discussions and see if it's sufficient.

[Discussions have been enabled](https://github.com/EasyDynamics/oscal-react-library/discussions).
