### ISSUE TITLE
Handle Markdown in Prose and Other Fields

### ISSUE THREAD

**Issue by hreineck** [EasyDynamics/oscal-react-library#156]
As a user involved in the governance, risk, and compliance of systems and components exploring controls, I want the prose of control statements, guidance, and other components that may use the [markup type](https://pages.nist.gov/OSCAL/reference/datatypes/#markup-multiline) to be in a neat and human-readable format.

## Acceptance Criteria
- Instances of markdown appearing in areas specified below are handled in a reasonably clean and readable way:
  - Emphasized text is bolded or italicized, or the * characters are simply removed.
  - Hyperlinks are implemented, or the parentheses/brackets characters are removed
  - If any other instances of markdown are identified eg. quoted, subscripted, or superscripted text they are handled in a clean and readable way.
- The following fields should support markdown:
  - Prose statements
  - Metadata Title
  - System Implementation remarks
  - Control Implementation descriptions (SSP and Component Definition)
- A (lightweight) architectural decision record (see [examples](https://github.com/EasyDynamics/easygrc-infrastructure/tree/main/doc/adr)) has been created that describes our choice of Markdown renderer and specifically talks to the security aspects of that library 

## Implementation Notes

Some examples of markdown appearing as plain text in the [800-53 rev5 catalog:](https://raw.githubusercontent.com/usnistgov/oscal-content/master/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json)

![image](https://user-images.githubusercontent.com/43356777/129962705-85fd8f8d-5c67-4f5f-971b-5e788d176b15.png)

![image](https://user-images.githubusercontent.com/43356777/129962790-7cd27126-695a-47c7-b91a-5bde348002b9.png)

Markdown also appears in the prose of several of the guidance buttons:

![image](https://user-images.githubusercontent.com/43356777/129962950-40c71ee2-7341-4cf8-b963-161e3a57a5c5.png)

**Comment by kylelaker** [comment]
Markdown + the `url` parameter needs to be careful to not accidentally open up an XSS vulnerability.

**Comment by kylelaker** [comment]
https://marked.js.org/ or something like it could be an option. But we'd definitely want to sanitize and probably find a way to strip any `<script>` or maybe even `<style>` tags in a sanitization process (since many Markdown parsers support raw HTML). A nice thing about Markdown is that it's fairly readable as-is without being rendered. We may want to consider using workers to asynchronously perform the rendering as well and we can cancel them if they work for too long.

What we really want to avoid is me being able to make a "malicious" control catalog and passing around links that load scripts or that make the UI thread lock up rendering markdown. Of course, the other thing would be if our default catalog that we load had a buggy markdown somewhere that did the same thing.

I am maybe being a little overly cautious here. There are probably other places that we're loading data from the internet and displaying it to users but this is one where we have far less control over the rendering pipeline.

**Comment by kylelaker** [comment]
https://github.com/remarkjs/react-markdown is another possible render.

**Comment by tuckerzp** [comment]
@schen2166 & @kperk103 I wanted to also post the rough plan for getting this done here so more people can see. 

1. Create the `OSCALMarkdownProse` component 
    - At the most basic level it would export a `ReactMarkdown` component [remarkjs/react-markdown: Markdown component for React (github.com)](https://github.com/remarkjs/react-markdown)
    - It probably should deal with both viewing/editing in markdown in some way? I am not 100% on this aspect and think you two may know a bit more than me on it.
    - Tests should be easy and also means we do not have to actually implement it anywhere to merge in this pr
    - A very initial draft pr should be made by tomorrow afternoon. This can be **extremely basic**. Just start getting discussion going since people will most likely have opinions on implementation.
2. Implement the component where it makes sense 
    - This will require some planning to split it up in a logical way
    - Hopefully your component makes this super easy to more or less just paste in
    - E2E tests should cover this and make it really easy? You might be able to get away with just component testing though.

Lets try to keep as much of the discussion on planning here and to use draft prs a lot. I think this task should be pretty easy with good planning but could easily get a little messy.

**Comment by kylelaker** [comment]
> * It probably should deal with both viewing/editing in markdown in some way

Any sort of complicated editing capabilities are not required as part of the initial implementation of markdown support. Only viewing is necessary for the initial component.

**Comment by schen2166** [comment]
Issue #556 is another subtask where there was markup written in prose in the backmatter. The commit there addresses the necessary changes for the backmatter

**Comment by naiqbal** [comment]
@kylelaker @brian-easyd Demo of Issue #156 for acceptance https://easydynamics-my.sharepoint.com/:v:/p/niqbal/EVohd_Csn51OnQ09gFAH2osB65GDEKvCnjOI69rnAWNQ9A?e=ysfjUo

**Comment by brian-easyd** [comment]
I agree this is complete
