### ISSUE TITLE
Remove File Type Mismatch Workaround

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#158]
See:
* usnistgov/oscal-content#59

We should remove the workarounds when those issues have been fixed.

**Comment by kylelaker** [comment]
This has been fixed on the `main` branch of the project and therefore I am going assign this to a milestone so we can track the work on it. We don't currently reference tagged released upstream anyway and staring at the now mostly dead code for `fixJsonUrls` just makes me a little sad.

For reference, the workaround to remove is https://github.com/EasyDynamics/oscal-react-library/blob/88369138a6a8059a2bc7238a01c1bc52543e69a6/src/components/oscal-utils/OSCALLinkUtils.js#L3-L12

All references will need to be updated as well. Anything that tests _specifically_ that function alone (or its behavior of rewriting URLs ending in `.xml`->`.json` can be removed); though we should continue to test that functionally all SSPs from `oscal-content` repository continue to display properly.

**Comment by brian-easyd** [comment]
@kylelaker Ultimately referencing a XML OSCAL file from a JSON OSCAL file's import statement is valid and should be handled by our tool. 

We can't count on every OSCAL file existing in both XML and JSON. Having the tool simply change the ".xml" to ".json" in the file is a fair work-around specifically for the NIST issue. 

Ultimately the tool should recognize the XML extension and convert the XML file to JSON, then process it. I suppose as a shortcut, it could look for a JSON version as described in the workaround above before converting; and only convert if no JSON file was found. 

In any case, I believe this issue, as written, has been addressed and should be closed. A new issue should cover the more complete functionality.

**Comment by brian-easyd** [comment]
Closing as discussed with @kylelaker
