### ISSUE TITLE
Reload Button Stays Disabled on Failed URL Fetch

### ISSUE THREAD

**Issue by hreineck** [EasyDynamics/oscal-react-library#163]
When a URL is entered that leads to a failed fetch or other error during loading, the reload button stays greyed out, preventing the user from entering a new URL:

![image](https://user-images.githubusercontent.com/43356777/132062877-6d7dc375-8f90-450d-b965-a3d172278d58.png)

## Steps to Reproduce

1. Enter an invalid url into any of the four URL bars.
2. Press reload.

OR navigate to a link with an invalid url such as:
https://oscal-viewer.msd.easydynamics.com/catalog?url=goofy

## Acceptance Criteria

The reload button is still enabled even when the error message is displayed.

## Implementation

This likely has to do with the `isLoaded` or `isResolutionComplete` state variables in `OSCALLoader.js`

**Comment by kylelaker** [comment]
More broadly, this bug is triggered any time the "Yikes!" text appears.
