### ISSUE TITLE
Investigate FedRAMP SSP Templates

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#190]
As a user of the OSCAL Viewer app I want to understand if there will be any usability issues with SSPs based on the latest [FedRAMP template](https://github.com/GSA/fedramp-automation/blob/master/dist/content/templates/ssp/json/FedRAMP-SSP-OSCAL-Template.json) and latest viewer code, so that I can be sure there are no limitations in leveraging the viewer for my SSP.

### Acceptance Criteria
- Any limitations of the current viewer app are documented here
- Any UX improvement ideas not already present in the backlog are documented here

**Comment by hreineck** [comment]
### Limitations of the Viewer by section:

Metadata:
- `revisions` are specified but not displayed anywhere in the Viewer.
- The `roles` that `parties` are linked to contain a `description` field that is not displayed.
- `parties` contains contact information, such as links to a `location` attribute in `metadata`, that are not displayed.
- The template uses links to Back Matter for party logos, which are unused by the Viewer.

System Characteristics:
- The `system-name-short` (abbreviated name) and `description` attributes are not displayed.
- `network-architecture` and `data-flow` attributes are not displayed. These contain links to diagrams.

System Implementation:
- `leveraged-authorizations` attribute is specified but not displayed.

Control Implementation:
- Extra `props` are added to controls, such as `control-origination` and `implementation-status` that are unused by the Viewer.
- A `responsibilities` attribute is added to some controls that is not displayed.

### Possible UX Improvements:

- There may need to be a UI element added to display extra `props` of controls.

- `network-architecture` and `data-flow` sections of System Characteristics are meant to contain diagrams; these would be best represented inline with their descriptions.

- Increasing the size of the Parties in Metadata could allow for more contact information to be displayed.

**Comment by rgauss** [comment]
@hreineck, this looks great!  Thanks.
