### ISSUE TITLE
Add Legend for Parameter Color-Coding

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#195]
As a user of the OSCAL React components and/or example viewer, I want to be able to see a legend of what the color-coding of parameters within controls and control implementations means so that I can quickly understand the context of parameter placeholders vs parameter values.

### Acceptance Criteria
- A legend is displayed that indicates the color coding of parameter placeholders vs parameter values.
- `react-testing-library` tests are in place

### Implementation Notes
- This could likely just be two rounded color squares of orange and blue with lightly colored text indicating `Placeholder` vs `Value` in the top-right corner of the control.

### Subtasks
- [ ] #427
- [ ] #428

**Comment by jgomez352** [comment]
@rgauss , Adding context through a pop-up or tooltip regarding the color coding will make the tool feel more intuitive.  Custom tooltips per control could be added later down the line, but an overarching tooltip for starters would be a huge fix involving a minor update to the code.

**Comment by Bronstrom** [comment]
@rgauss The Implementation Notes specify the legend be placed in the top-right corner of a control, which I have finished implementing. This legend appears in the same place on every control, which seems a bit repetitive depending on the number of controls. From a UX standpoint, would it be better to have the legend appear once at the same level of the title of a control grouping (catalog control group, control implementations, imported controls)?

**Comment by rgauss** [comment]
@Bronstrom, sure that's fine for now if it looks better.

That area of UI/UX will change drastically in #87 and #88 at which time we'll want to re-evaluate placement.

**Comment by naiqbal** [comment]
@Bronstrom Let me know when you complete this so we can close it out.
