### ISSUE TITLE
Viewer Breaks on Basic Catalog

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#227]
The viewer app currently breaks when trying to view the example [basic-catalog.json](https://github.com/usnistgov/oscal-content/blob/master/examples/catalog/json/basic-catalog.json).

### Steps to Reproduce
1. Navigate to the Catalog Viewer page
2. Paste in the [raw link for the basic-catalog](https://raw.githubusercontent.com/usnistgov/oscal-content/master/examples/catalog/json/basic-catalog.json)
3. Click Reload

### Expected Behavior
4. The catalog renders

### Actual Behavior
5. A blank page is returned (and the browser console shows errors)

**Comment by kylelaker** [comment]
Specifically, we're seeing:

```
TypeError: Cannot read properties of undefined (reading 'map')
    at jt (OSCALCatalogGroup.js:42:12)
    at oi (react-dom.production.min.js:157:137)
    at Ul (react-dom.production.min.js:267:460)
    at Cc (react-dom.production.min.js:250:347)
    at Sc (react-dom.production.min.js:250:278)
    at Ec (react-dom.production.min.js:250:138)
    at vc (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Vo (react-dom.production.min.js:122:325)
ll @ react-dom.production.min.js:216
```

which points to https://github.com/EasyDynamics/oscal-react-library/blob/682b06182c61328cc1bad506bdd3185f9d58ce83/src/components/OSCALCatalogGroup.js#L42.

Hopefully we can change the `.map` to `?.map` but we're going to want to look at the assumption being made there (that `controls` is always defined on `group`) and identify the proper fix (and it may be more proper to fix this "higher up" in the stack).

If the `basic-catalog.json` does not comply with the spec, perhaps there's an opportunity to submit a patch upstream as well.

In general though, we should be defensive against invalid inputs and so we probably want to err on the side of accepting null/undefined values regardless.

**Comment by kylelaker** [comment]
It looks like the structure of `basic-catalog.json` is:

```
catalog: {
  groups: [
   {
     groups: [
       {
         controls: ...
       }
    }
}
```

Per [the specification](https://pages.nist.gov/OSCAL/reference/latest/catalog/json-reference/#/catalog/groups/groups) it is totally fine for a group to contain other groups (and it seems, infinitely embedded); however, we do not seem to be accounting for embedded groups here. If we perform the simple change of `.map` -> `?.map` we'd get a mostly-empty page:

![image](https://user-images.githubusercontent.com/850893/151175518-ffa8491d-caf4-4bf0-bcbe-ffa211cb17d3.png)

For reference, neither the NIST SP 800-53r4 nor SP 800-53r5 catalogs utilize embedded groups which is why we likely haven't encountered this before.

**Comment by kylelaker** [comment]
I've started some basic work to fix this on the [`feature/handle-embedded-groups`](https://github.com/EasyDynamics/oscal-react-library/tree/feature/handle-embedded-groups) branch; however, there are some issues which are mentioned in the commit message (see 2bfc8a667be04781434c20d736e6056bd4249b9a) and the screenshot below 
![image](https://user-images.githubusercontent.com/850893/151181376-79820b36-5308-4098-b879-9e5cda98e414.png)

I'm not sure I can commit to carrying this to completion so anyone else is welcome to take over that branch (or find a far better approach and ignore mine completely 😄)
