### ISSUE TITLE
Profile/Catalog Set Parameter Values Not Displayed

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#312]
OSCAL Catalogs and Profiles are permitted to specify `values` within `set-parameter` instances.  Those values are currently ignored and not displayed in the Profile or Catalog viewer control prose, only the parameter labels from the Catalog are displayed.

### Steps to Reproduce
1. Use the Profile viewer to load an OSCAL Profile that contains `set-parameter.values`

### Expected Behavior
2. The Profile parameter values are displayed

### Actual Behavior
3. The Catalog parameter labels are displayed

**Comment by rgauss** [comment]
The expected behavior was confirmed in a discussion in the OSCAL Dev Lunch working group on 2022/03/10.

**Comment by kylelaker** [comment]
Can a profile have a `set-parameter` with a name the same `param-id` as one in the catalog? If so, it is a shared namespace or distinct? If shared, which takes precedence?

**Comment by rgauss** [comment]
> Can a profile have a `set-parameter` with a name the same `param-id` as one in the catalog? If so, it is a shared namespace or distinct? If shared, which takes precedence?

Yes, the `param-id` in a Profile will often match a `param-id` from a Catalog, and that's the mechanism by which Profiles can do things like add additional constraints to a Catalog parameter.

For example, in 800-53 Catalog, AC-12 Session Termination, param-id `ac-12_odp` has a label of `conditions or trigger events`, which when inserted in prose reads as:
> Automatically terminate a user session after < conditions or trigger events >.

A Profile might then specify `set-parameter` `constraints` for `ac-12_odp` that requires that value to be `15 minutes or less`.

This issue describes the scenario where Profiles might `set-parameter` `values`, for example `15 minutes`, indicating that all SSPs importing that Profile have been configured for session termination of 15 minutes.  There was further discussion on this in the working group, where I suggested that should really be a constraint in the Profile, and that SSPs should be forced to indicate they have satisfied that constraint with a value of `15 minutes`, even if the constraint is `exactly 15 minutes`.

However, as the spec stands Catalogs and Profiles can set parameter values, so we should render them as such.
