### ISSUE TITLE
Vulnerabilities in Outdated Transitive Dependencies

### ISSUE THREAD

**Issue by hreineck** [EasyDynamics/oscal-react-library#317]
Several of this package's dependencies contain outdated transitive dependencies that have known security vulnerabilities as detected by [dependabot alerts](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/about-alerts-for-vulnerable-dependencies).

While these vulnerabilities likely do not pose any risk the way these dependencies are currently used, they may be a barrier to the adoption of this library.

## Implementation Notes

This issue cannot be directly addressed at this time, because as of now all of the dependencies that contain these transitive dependencies are updated to their latest versions.
Once new versions of these packages are available that address the vulnerabilities, the vulnerabilities can be resolved by updating these packages:

### The transitive dependencies with vulnerabilities are:
* `prismjs`
* `postcss`
* `nth-check`
* `glob-parent`

### Our dependencies that depend on the above packages:
* `storybook`  (many packages under storybook)
* `react-scripts`
* `microbundle-crl`

## Workaround

Components of the library can potentially be used without installing the above packages. For example, `storybook` is only used to publish changes to our official documentation and is not necessary for using the UI elements on their own. 
Investigation should be done into making these dependencies optional if possible

**Comment by kylelaker** [comment]
Looks like despite `storybook` updating to 6.5.0 in #399 we actually _gained_ one more issue... 

```
@storybook/react@6.5.0 requires trim-newlines@^1.0.0 via a transitive dependency on meow@3.7.0
@storybook/preset-create-react-app@4.1.0 requires trim-newlines@^1.0.0 via a transitive dependency on meow@3.7.0
```
🙄

**Comment by naiqbal** [comment]
Come back to this issue at a later date - 7/1/22

**Comment by kylelaker** [comment]
As of #651 and #652 this is resolved!! We have no open Dependabot security warnings on this repository and `npm audit` should mostly be clean as well!
