### ISSUE TITLE
`dependency-pr` workflow job condition never evaluates to true

### ISSUE THREAD

**Issue by kylelaker** [EasyDynamics/oscal-react-library#321]
In https://github.com/EasyDynamics/oscal-react-library/actions/workflows/dependency-pr.yml, we can see that the workflow itself is being triggered but the _job_ is being skipped. This implies that the condition isn't quite right at at

https://github.com/EasyDynamics/oscal-react-library/blob/46e2909c1f0b233056f7bfb32fae36be93507fe2/.github/workflows/dependency-pr.yml#L16

We've already enabled debug log output for this workflow; however, it doesn't seem that condition evaluation for un-run jobs gets logged.

### Acceptance Criteria

 - The existing `update` job within the `dependency-pr` workflow properly gets executed when the a PR modifying the top-level `package-lock.json` file in the repository gets merged to `develop`.

### Implementation Notes

We may want to consider adding another job that dumps `${{ github.event }}` as a JSON object to stdout and see what the values we're using actually _are_.

**Comment by kylelaker** [comment]
lol well now it evaluates to true but it doesnt actually trigger jobs on the subsequent run... maybe it'd be better to just use on `on.schedule.cron` trigger and just do this daily.

**Comment by kylelaker** [comment]
Okay so we probably want to look at https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens so that we can attach this to the organization. Then, we can rework the workflow to use the App Token to create PRs. The App route is probably best because it allows for attaching to the organization instead of to a person and because it allows `on: pull_request_target`.

**Comment by naiqbal** [comment]
@rgauss Can we move this to done since it was closed?
