### ISSUE TITLE
Update to React 18

### ISSUE THREAD

**Issue by kylelaker** [EasyDynamics/oscal-react-library#364]
[React 18 was released last month](https://reactjs.org/blog/2022/03/29/react-v18.html) and it brings some features for concurrent rendering that might be cool. It's also generally good to keep our dependencies up-to-date. React 18 brings some new concurrent rendering capabilities.

### Implementation Notes

 - We have a lot of dependencies tightly coupled to React, we need to make sure they all work together (including `@testing-library/react`, `react-scripts`, and `react-dom-router`)
 - There is a blog post on [How to Upgrade to React 18](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html)

### Acceptance Criteria

 - React 18 is used without any known regressions
 - The [new Root API](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis) has been adopted
 - Ensure current testing is sufficient to validate successful upgrade. Adjust testing if necessary.
 - Ensure no tests fail related to components use of new version.

**Comment by kylelaker** [comment]
`react-ga` was another one that caused dependency conflicts but that's resolved in #449

**Comment by kylelaker** [comment]
We have started to see test failures on the `oscal-editor-deployment` repository that coincide with the merging of the React 18 upgrade. I don't want to move forward with closing this task until we're sure those tests are passing correctly.

**Comment by Bronstrom** [comment]
I haven't been watching the test failures closely on `oscal-editor-deployment` lately. Are we still thinking they could be failing as a result of us updating to React 18 @kylelaker?
