### ISSUE TITLE
Migrate from `create-react-library` and related tools

### ISSUE THREAD

**Issue by kylelaker** [EasyDynamics/oscal-react-library#403]
As of April 2022, `create-react-library` and its associated tools are [no longer supported](https://github.com/transitive-bullshit/create-react-library#2022-update). The author of that library created a [blog post comparing related tools](https://transitivebullsh.it/javascript-dev-tools-in-2022#823feddaa1bb4edea19042852b0a5b54). We should look into those tools and pick one that fits our current (and future) needs and investigate performing a migration.

**Comment by hreineck** [comment]
Reading through the linked blog post, https://github.com/nrwl/nx seems like a good option as it has lots of support and documentation on creating React apps, as well as features for multiple projects in one repo ie. our React library + example.
It does a lot of stuff, so maybe it'd be bulky or overkill.
https://github.com/developit/microbundle seems like another viable option.
