### ISSUE TITLE
Display SSP Users/Personas

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#404]
As a user of the `OSCAL Viewer`, I want to be able to see all users/personas defined in the `SSP` system implementation I am viewing. 

### Acceptance Criteria
- [ ] List of users appears above `Component` list. 

### Implementation Notes
- Editing will not be required for this increment. 
- https://github.com/EasyDynamics/oscal-demo-content/blob/main/system-security-plans/ssp-example.json#L128-L152

**Comment by mikeisen1** [comment]
@rgauss, does this issue relates to users as defined [here](https://pages.nist.gov/OSCAL/reference/latest/system-security-plan/json-reference/#/system-security-plan/system-implementation/users)?

**Comment by hreineck** [comment]
> @rgauss, does this issue relate to users as defined [here](https://pages.nist.gov/OSCAL/reference/latest/system-security-plan/json-reference/#/system-security-plan/system-implementation/users)?

Yes; these live in `system-implementation/users`
