### ISSUE TITLE
Display Parties Contact Information

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#405]
### Acceptance Criteria 
- [x] Discussion of design is documented on this task
- [x] Parties Information is displayed

**Comment by mikeisen1** [comment]
The parties field as defined [here](https://pages.nist.gov/OSCAL/reference/latest/system-security-plan/json-reference/#/system-security-plan/metadata/parties), references `email-addresses`, `telephone-numbers`, and `addresses`.

The `telephone-numbers` and `addresses` fields contain a `type` field, which should be displayed in addition to the relevant information.

**Comment by Bronstrom** [comment]
Adding additional information underneath the name/role title of an `OSCALMetadataPartiesCard` party would likely cause the data to get a bit cluttered. It would be a good idea to a new UI feature here.

Two ways of implementing the UI of this issue:

1. After selecting a `party`, additional contact information is displayed beneath it like a dropdown. An arrow indicator could also be displayed next to a party indicating it as a dropdown.
2. After selecting a `party`, a dialog content box appears displaying the party selected and with additional contact information. (This is similar to how a dialog box appears when selecting "Guidance" of an `OSCALControl`).

**Comment by tuckerzp** [comment]
I think using https://mui.com/material-ui/react-card/ would make displaying more information a lot nicer. `CardActions` also allows for further information to be displayed.

**Comment by tuckerzp** [comment]
Integration testing still needs to be done https://github.com/EasyDynamics/oscal-editor-deployment/pull/156 before we close this.
