### ISSUE TITLE
Display Control Props

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#406]
### Description 
As an owner or reviewer of an OSCAL object, I want a display of the props of controls so that I can view all of the information relevant to a given control.

### Acceptance Criteria
- When viewing an SSP, the Control Implementation section of the OSCAL Viewer displays the props of each control.
- The tests are updated to demonstrate the new functionality

### Implementation Notes
Each element of the `control-implementation/implemented-requirements` of an SSP may contain a `props` attribute.
Displaying these is likely very similar to how we display `props` in the System Implementation section of the OSCAL Viewer.

**Comment by brian-easyd** [comment]
Props have different meaning in different context, and are often intended as metadata for tools rather than display to users. They need to be handled on a per-assembly basis. 

Closing this issues in lieu of prop management that better aligns with specific circumstances.

**Comment by tuckerzp** [comment]
> Closing this issues in lieu of prop management that better aligns with specific circumstances. 

@brian-easyd should this be closed as unplanned rather than completed?
