### ISSUE TITLE
Display Metadata Role Descriptions

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#408]
### Description 
As a user of an OSCAL object, I want a display of the description of the "role" of each party in the metadata section so that I can understand what each party's responsibilities are.

### Acceptance Criteria
- If a party has a role with a description, both the role title and role description are displayed in the metadata React component
- The tests are updated to demonstrate the new functionality

### Implementation Notes
The OSCAL Viewer currently displays the `title` of a given role in `metadata/roles` -- the object may also have a `description` attribute, in which case it should be rendered in addition to the title.

**Comment by tuckerzp** [comment]
Design should be done in parallel with #405

**Comment by tuckerzp** [comment]
### Status update

I think that this task is between 50% - 80% done, however the percentage could change a bit depending on how the team feels about the design and elegance of the code. 

### Details

It technically does display the role description now so it could be considered very close to done. There are however questions on how clean the solution is that will need to be discussed after I handle the design. Currently I am working on making the display look nice. I think I am pretty close on that, but the React components I am using are also acting a bit weird. I do have a few potential designs I will play around with to see if I can circumvent those issues.

**Comment by Bronstrom** [comment]
3/10/23 Sprint Planning - Moved from Sprint 42 to Sprint 43
