### ISSUE TITLE
Display SSP System Short Name and Description

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#410]
As a user consuming OSCAL React Library, I would like to see the [short name](https://pages.nist.gov/OSCAL/reference/latest/system-security-plan/json-reference/#/system-security-plan/system-characteristics/system-name-short) of my system displayed along with the [description](https://pages.nist.gov/OSCAL/reference/latest/system-security-plan/json-reference/#/system-security-plan/system-characteristics/description) of my system.

## Implementation Notes

Typically the short name will be an acronym of the name. This could just be displayed within parentheses to the right of the name when provided.

The description would ideally be displayed beneath the name of the system name. This could be displayed in a Material UI `Grid` spanning the full with of the System Characteristics `Card`, where the description is displayed on the left, and the `deployment-model` and `service-models` or displayed on the right.

**Comment by hreineck** [comment]
Closed by https://github.com/EasyDynamics/oscal-react-library/pull/611
