### ISSUE TITLE
Display Metadata Party Logos

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#411]
### Description 
Certain parties represent organizations or companies. In some OSCAL examples, namely the [FedRAMP SSP Template](https://github.com/GSA/fedramp-automation/blob/master/dist/content/templates/ssp/json/FedRAMP-SSP-OSCAL-Template.json), a link to the logo is provided. As a user of such an OSCAL object, I want the logo to be displayed so that I can verify that it is included in the OSCAL object and that it is properly functioning.

### Acceptance Criteria
- The metadata React component displays the logo of any parties that have linked a logo
- The tests are updated to demonstrate the new functionality

### Implementation Notes
Party logos live in OSCAL Components, Catalogs, Profiles, and SSPs as links in `back-matter`, with a direct link to the logo image in its `rlinks`.
An object in `metadata/parties` can link this logo with an element in its `links` attribute, which is an object with:
- `href`, pointing to the `uuid` of the above object in `back-matter`
- and `rel`, set to `logo`

**Comment by kylelaker** [comment]
Perhaps we can use https://mui.com/material-ui/react-card/#media to display this in the `Card`s for each Party

**Comment by brian-easyd** [comment]
Deferring until we have a UI person to weigh in on the best handling of logos.

**Comment by emcathow** [comment]
I recommend placing the logos inside of the "details" modal. 

It will still be easily accessible, and logically grouped with organizational information. 

Example mockup: 
<img width="401" alt="image" src="https://user-images.githubusercontent.com/128419623/235227694-9acb3ecb-f59d-47b5-97b5-1bb91e3bb1c0.png">
