### ISSUE TITLE
Eliminate Warnings in Browser and Tests

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#414]
We should investigate eliminating any remaining warnings (such as from `npm run test` or browser debug console) once #244 is complete.

### Subtasks
- [x] #425
- [x] #426
- [x] #446
- [x] #450

**Comment by kylelaker** [comment]
@tuckerzp Yeah that message appears in the logs. I'd look at the MUI update https://github.com/EasyDynamics/oscal-react-library/runs/6812426449?check_suite_focus=true#step:7:239

**Comment by kylelaker** [comment]
@tuckerzp specifically mui/material-ui#33134 should resolve these new warnings and hopefully the next update to the `mui/labs` package will take care of that new warning

**Comment by kylelaker** [comment]
MUI [v5.8.4](https://github.com/mui/material-ui/releases/tag/v5.8.4) has been released which has a fix for that set of `forwardRef` issues. Hopefully our bot picks up that change at ~8:30 ET today.

**Comment by tuckerzp** [comment]
#414 fixed the additional error!

**Comment by naiqbal** [comment]
@rgauss good to move over?
