### ISSUE TITLE
Publish Package workflow is not automatically triggered by release workflow

### ISSUE THREAD

**Issue by kylelaker** [EasyDynamics/oscal-react-library#418]
When the [Release workflow](https://github.com/EasyDynamics/oscal-react-library/blob/develop/.github/workflows/release.yml) completes, the [Package publish workflow](https://github.com/EasyDynamics/oscal-react-library/blob/develop/.github/workflows/publish-package.yml) is not automatically triggered.

### Acceptance Criteria

Creating a release results in _that release_ **automatically** being published to NPM and GitHub Packages.

### Implementation Notes

This is likely because (as we've seen in other situations), `push`es by a `GITHUB_TOKEN` from GitHub Actions do not further trigger other GitHub Actions. So we likely just need to use the GitHub automation app to perform the release.

**Comment by brian-easyd** [comment]
Closing unworked (withdrawn)
