### ISSUE TITLE
Control Info for SSP Control Parts are not Displayed for All Components

### ISSUE THREAD

**Issue by hreineck** [EasyDynamics/oscal-react-library#421]
If a given control has statements that are under a decimal-numbered control statement (eg. AC-2.2), the OSCAL Viewer and Editor will not display the parameters or descriptions that are given for that statement.

### Acceptance Criteria
- A properly formatted OSCAL SSP that includes a parameter and description for a decimal-numbered control part (eg. AC-2.2) renders those parameters and description in both the OSCAL Viewer and OSCAL Editor

### Implementation Notes
As far as I can tell this case is untested, probably because the [SSP example](https://github.com/EasyDynamics/oscal-demo-content/blob/main/system-security-plans/ssp-example.json) in the demo-content repo only includes control AU-1 - this means that *decimal numbered* control parts such as AC-2.1 were not considered in our test data.

To demonstrate this bug, I created an updated example SSP which you can see in this PR: https://github.com/EasyDynamics/oscal-demo-content/pull/17

The relevant part is this commit: https://github.com/EasyDynamics/oscal-demo-content/pull/17/commits/9636de938d8f8c8b96c2d05816f3d89988cbdc46
What this does is add dummy data for a parameter and description in AC-2.2. 
When viewed in the OSCAL Viewer, however, you will see that the parameters of AC-2.2 remain blank despite a parameter being set.
![image](https://user-images.githubusercontent.com/43356777/176932098-8f9cac28-03be-4c02-9856-31b47be3e0d0.png)
This effect is the same in the OSCAL Editor as well, in which case the parameter and description fields are blank when the "edit" icon is clicked:
![image](https://user-images.githubusercontent.com/43356777/176932307-db3e46ad-3e92-4ec7-b3a2-a3b833a041e7.png)

We should test this by expanding the existing test data to encompass deeper levels of the controls.

**Comment by naiqbal** [comment]
@hreineck Could you add the screenshots for this one when you get a chance?

**Comment by hreineck** [comment]
Something that may complicate this a bit, but not entirely necessary for acceptance criteria (because it is caused by an improperly-formatted OSCAL file) is that if [the component-uuid of AC-2.2](https://github.com/EasyDynamics/oscal-demo-content/pull/17/commits/9636de938d8f8c8b96c2d05816f3d89988cbdc46#diff-4af774fff0b11af5c31442071c27e037c1a4f86f4ef501fa96c422391f04d33cR396) is removed from the file, the description and parameter will render as intended for ALL components.
This seems to be related to https://github.com/EasyDynamics/oscal-rest-service/issues/100
