### ISSUE TITLE
Document selection form not displaying title updates

### ISSUE THREAD

**Issue by mikeisen1** [EasyDynamics/oscal-react-library#433]
When in edit mode, if an SSP, Component Definition, Catalog, or Profile title is modified, the document selection form which displays the titles of the OSCAL documents that can be viewed does not update the title of the OSCAL document being modified.

### Steps to Reproduce
- Run Viewer in edit mode and backed service
- Navigate to any OSCAL document viewer and select an OSCAL document
- Edit the title and click save
- Check the file selection form at the top of the page and see that the titles do not match

### Acceptance Criteria
- The file selection form displays an updated title on a successful save of a modified title

**Comment by kylelaker** [comment]
This is an issue in the `OSCALLoaderForm`. It does not refresh at all when a POST operation (or really any API operation) is performed. Ideally (in my opinion), we'd probably just re-`GET` the list of documents and then transparently re-select the one with the same UUID as the one we've been working on. Another solution that may work would be to sorta hackily pass that one bit of data to `OSCALLoaderForm` but that feels like a lot of useless state. Of course, even telling `OSCALLoaderForm` that it needs to reload in the first place requires some state magic maybe.

**Comment by rgauss** [comment]
I've mentioned this issue in the past, and that we'll be completely reworking object selection in #305, so I think we should spend effort there rather than fixing this.
