### ISSUE TITLE
Subtask: Storybook with `Object Selector`

### ISSUE THREAD

**Issue by tuckerzp** [EasyDynamics/oscal-react-library#469]

**Comment by kylelaker** [comment]
Unfortunately, it seems like this may not be possible in the current state of the application. This component will require the Storybook to have a backend server defined but we don't really have a good means to do that in Storybook today. Thanks for your work on this @kperk103 and sorry we didn't catch that sooner.

I am going to close this as "not planned". We can reconsider some day as part of a more holistic solution (for example, allow viewing _any_ editable components in Storybook in their editing state).
