### ISSUE TITLE
Update or remove all `TODO`s in the code base

### ISSUE THREAD

**Issue by kylelaker** [EasyDynamics/oscal-react-library#492]
Throughout the code base, there are many `TODO` comments that reference old Jira tickets (we are no longer using Jira) or that are no longer applicable to the surrounding code.

For every `TODO` in the code base, we need to make sure that a GitHub issue exists for it; then we need to decide whether referencing the `TODO` in the code is appropriate (it very well may not be) and either update or remove it as appropriate.

**Comment by kperk103** [comment]
Here are the `TODO`s that are a bit vague:
https://github.com/EasyDynamics/oscal-react-library/blob/c693badc2d80447eb9136e23c7c7e825cde9faf4/src/components/OSCALControl.js#L10
https://github.com/EasyDynamics/oscal-react-library/blob/c693badc2d80447eb9136e23c7c7e825cde9faf4/src/components/OSCALControlPart.js#L17
https://github.com/EasyDynamics/oscal-react-library/blob/c693badc2d80447eb9136e23c7c7e825cde9faf4/src/components/oscal-utils/OSCALProfileResolver.js#L44
https://github.com/EasyDynamics/oscal-react-library/blob/c693badc2d80447eb9136e23c7c7e825cde9faf4/src/components/oscal-utils/OSCALProfileResolver.js#L48
https://github.com/EasyDynamics/oscal-react-library/blob/c693badc2d80447eb9136e23c7c7e825cde9faf4/src/components/oscal-utils/OSCALSspResolver.js#L28

**Comment by kperk103** [comment]
I have created a few GitHub issues for `TODO`s, however some of the issues may be a bit confusing. I'm attaching them here so that others can look at them and provide some clarification if necessary.
https://github.com/EasyDynamics/oscal-react-library/issues/498
https://github.com/EasyDynamics/oscal-react-library/issues/499
https://github.com/EasyDynamics/oscal-react-library/issues/501
https://github.com/EasyDynamics/oscal-react-library/issues/502

**Comment by jed-exotic** [comment]
Wish the one's labeled as "should be improved" are quite vague. What are the use cases? For both of these, they can be tracked in a planning task i.e. "identify additional use cases for ___".

The 800-53 specific questions are interesting, if EasyGRC is intended to be used with other frameworks we should abstract away those from the main logic, and pull them in based on user input.
