### ISSUE TITLE
Clean up "by-id" check

### ISSUE THREAD

**Issue by kperk103** [EasyDynamics/oscal-react-library#498]
Different ways to represent control modifications in OSCAL make the `isRelevantID()` check for determining `controlParts` needed in `OSCALControlModification.js`. Certain implementations specify the control ID in the "by-id" field for top-level modifications, others leave "by-id" undefined. This should be cleaned up at some point if these differences are resolved.

https://github.com/EasyDynamics/oscal-react-library/blob/c693badc2d80447eb9136e23c7c7e825cde9faf4/src/components/OSCALControlModification.js#L92-L94

**Comment by tuckerzp** [comment]
To provide some context from the [JSON outline](https://pages.nist.gov/OSCAL/reference/latest/complete/json-outline/), `by-id` is not strictly needed. 

Until the `by-id` field is required or there is another field to check for relevant id's, we may not be able to remove this check. 

![Web capture_9-8-2022_9570_pages nist gov](https://user-images.githubusercontent.com/39490074/183667962-911a2a36-482f-4b11-856c-b14ff5c58ffe.jpeg)

**Comment by kylelaker** [comment]
Generally, we need to make sure that we're complying with the OSCAL specification. We need to support _all_ the ways that these references can take place to remove. This may require EasyDynamics/oscal-react-library#89

**Comment by kylelaker** [comment]
This was handled in recent work that refactored how we handle modifications.
