### ISSUE TITLE
Remove code once OSCAL Content source issue is fixed

### ISSUE THREAD

**Issue by kperk103** [EasyDynamics/oscal-react-library#502]
Once OSCAL Content has fixed their issue with source, (https://github.com/usnistgov/oscal-content/issues/59), the following can be removed because it is a temporary fix for the source link error:
https://github.com/EasyDynamics/oscal-react-library/blob/87fe8416a683d4a2f4edabc68fcf4a8454b21ddd/src/components/oscal-utils/OSCALProfileResolver.js#L49-L55

**Comment by kylelaker** [comment]
@tuckerzp do you mind trying to add some detail to this? I know you've been working on looking at other NIST OSCAL content recently.

**Comment by tuckerzp** [comment]
Looking into it a bit, it seems to be fixed? At the very least, Ray's previous example is fixed now.
