### ISSUE TITLE
Populate implementationSetParameters

### ISSUE THREAD

**Issue by kperk103** [EasyDynamics/oscal-react-library#503]
When editing a statement within an `OSCALControl`, it is currently searches for values in `statementByComponent` for the `implementationSetParameters`:

https://github.com/EasyDynamics/oscal-react-library/blob/87fe8416a683d4a2f4edabc68fcf4a8454b21ddd/src/components/OSCALControlProse.js#L416-L420

We want to elaborate on this a little more and populate it with values from `statementByComponent` or empties in `OSCALControlProse`.

**Comment by Bronstrom** [comment]
From what I can tell this issue has been almost completed, if not yet already completed.

The TODO notes suggest to populate `implementationSetParameters` with values from `statementByComponent`. I'm unsure completely if this is referring to `setParameter` here, or `implementationSetParameters` (which is declared later in `OSCALRestUtils`).

I also want to note that it looks like a TODO note was added at the beginning of https://github.com/EasyDynamics/oscal-react-library/pull/387, and implementationSetParameters (which is declared later in `OSCALRestUtils`) was handled later in https://github.com/EasyDynamics/oscal-react-library/pull/396.

Please let me know if I am missing something here.

**Comment by Bronstrom** [comment]
In the case that this comment is suggesting to populate what is beneath the TODO comment, it makes most sense to validate what is contained underneath [`set-parameters` in the SSP JSON reference](https://pages.nist.gov/OSCAL/reference/latest/system-security-plan/json-reference/#/system-security-plan/control-implementation/implemented-requirements/set-parameters). There are three key-value pairs underneath `set-parameters`, and the only one not being validated is `remarks`; although, the cardinality of this is 0 to 1, so it seems like this doesn't need to be validated.

**Comment by Bronstrom** [comment]
For more detail on this issue if anyone is confused, I believe this was a `TODO` comment that was forgotten about and never removed. https://github.com/EasyDynamics/oscal-react-library/pull/396 addresses this `TODO`, which was left in https://github.com/EasyDynamics/oscal-react-library/pull/387. Also when there are no `set-parameter` `values` provided in `statementByComponent` an empty (null) array is assigned to `values`.
