### ISSUE TITLE
Support frameworks other than 800-53

### ISSUE THREAD

**Issue by kperk103** [EasyDynamics/oscal-react-library#504]
Some parts of the codebase, such as the following shown below, are [800-53 specific](https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final). If `oscal-react-library` is intended to be used with other frameworks, we would want to abstract away these 800-53 specific parts and pull them in based on user input.

https://github.com/EasyDynamics/oscal-react-library/blob/87fe8416a683d4a2f4edabc68fcf4a8454b21ddd/src/components/OSCALControl.js#L11-L14

https://github.com/EasyDynamics/oscal-react-library/blob/87fe8416a683d4a2f4edabc68fcf4a8454b21ddd/src/components/OSCALControlPart.js#L18-L19

## Implementation Notes
- Having the user predefine some kind of [context ](https://reactjs.org/docs/context.html) may be a possible solution? Depending on the framework you wish to display, there may be more or less of these framework specific checks. 
- An example of other frameworks you may wish to display with OSCAL could be HIPAA, GDPR, etc.

**Comment by tuckerzp** [comment]
I've changed the title and tags to encompass a larger task. I think that, while extracting those two 800-53 specific parts of the code somewhere else could be a small change, doing it in such a way that we can more easily support other frameworks in the future may take a bit more design and effort.

**Comment by kylelaker** [comment]
More generally, we want to be able to support "locally defined values", to follow the wording in the OSCAL specification. We may want to track some well-known locally defined values for specific authors, such as FedRAMP PMO or NIST. This should be a more generic and extensible solution for additional authors and perhaps pulling from some sort of standard/central repositor(y|ies) over time.

The latter is not necessary for MVP but making this more generic is a component of the initial implementation of this task.

**Comment by kylelaker** [comment]
These were both handled when we refactored how we handled properties. This is now all set.
