### ISSUE TITLE
Remove profile resolution relative URL workarounds

### ISSUE THREAD

**Issue by kperk103** [EasyDynamics/oscal-react-library#505]
We include a few profile link resolution solutions in `OSCALProfileResolver` using `itemUrl`:

https://github.com/EasyDynamics/oscal-react-library/blob/87fe8416a683d4a2f4edabc68fcf4a8454b21ddd/src/components/oscal-utils/OSCALProfileResolver.js#L45-L47

as well as in `OSCALSspResolver` using `profileUrl`:

https://github.com/EasyDynamics/oscal-react-library/blob/87fe8416a683d4a2f4edabc68fcf4a8454b21ddd/src/components/oscal-utils/OSCALSspResolver.js#L29-L31

Both of these can be removed if the links are resolved in the residing `oscal-content`.

**Comment by Bronstrom** [comment]
It appears https://github.com/usnistgov/oscal-content/issues/60 is now resolved. These couple of lines can be removed, although we must test the relative profile import functions correctly.

**Comment by tuckerzp** [comment]
> It appears https://github.com/usnistgov/oscal-content/issues/60 is resolved.

That seems to have fixed the replacement in `SSPResolver`, but it seems things may still be broken for `ProfileResolver`. 

When trying to load our [`ssp-example`](https://oscal-viewer.msd.easydynamics.com/system-security-plan?url=https://raw.githubusercontent.com/EasyDynamics/oscal-demo-content/main/system-security-plans/ssp-example.json) after removing the replacement, the items in the control implementation do not load. 

---

It seems that the replacement is called once when loading the `SSP`. 
```
originalItemUrl = null/../NIST_SP-800-53_rev4_catalog.json`

itemUrl = https://raw.githubusercontent.com/usnistgov/oscal-content/v1.0.0/nist.gov/SP800-53/rev4/json/NIST_SP-800-53_rev4_MODERATE-baseline_profile.json/../null/../NIST_SP-800-53_rev4_catalog.json`. 
```
