### ISSUE TITLE
Remove underscore replacement workaround

### ISSUE THREAD

**Issue by kperk103** [EasyDynamics/oscal-react-library#511]
Once the OSCAL example content is fixed, the underscore replacement in `OSCALControlResolver.js` can be removed. 
https://github.com/EasyDynamics/oscal-react-library/blob/b34991180dc344729d8de8952222de6b072cef79/src/components/oscal-utils/OSCALControlResolver.js#L54

**Comment by tuckerzp** [comment]
Looking at the issue https://github.com/usnistgov/oscal-content/issues/58, it seems this may have been resolved. We will need to test to ensure that removing this `replace` does not break anything before merging.
