### ISSUE TITLE
Remove missing media type workaround

### ISSUE THREAD

**Issue by kperk103** [EasyDynamics/oscal-react-library#512]
Once https://github.com/GSA/fedramp-automation/issues/103 has been closed, the workaround for missing media types can be removed in `OSCALBackMatter.js`. Currently, file extension is being used.
https://github.com/EasyDynamics/oscal-react-library/blob/b34991180dc344729d8de8952222de6b072cef79/src/components/OSCALBackMatter.js#L24-L27

**Comment by tuckerzp** [comment]
It looks like https://github.com/GSA/fedramp-automation/issues/103 is now closed.
