### ISSUE TITLE
`url` query string parameter is broken

### ISSUE THREAD

**Issue by kylelaker** [EasyDynamics/oscal-react-library#544]
### Description

The OSCAL Viewer application supports a `?url` query string parameter to pass a URL to an OSCAL document directly. This was described in #134 and implemented in #143.

### Steps to Reproduce

1. Go to any of:
  - https://oscal-viewer.msd.easydynamics.com/system-security-plan?url=https://raw.githubusercontent.com/GSA/fedramp-automation/master/dist/content/templates/ssp/json/FedRAMP-SSP-OSCAL-Template.json
  - https://oscal-viewer-dev.msd.easydynamics.com/catalog?url=https://github.com/usnistgov/oscal-content/blob/main/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json

### Expected behavior

The document specified from the `url` parameter is loaded.

### Actual Behavior

The default document URL from the application configuration is loaded.

### Additional Notes

I am not sure exactly when this broke but it was some time in the last few weeks. This is an important functionality to have working. Regression tests must be added in [`EasyDynamics/oscal-editor-deployment`](https://github.com/EasyDynamics/oscal-editor-deployment) to ensure this isn't unexpectedly broken again.

**Comment by tuckerzp** [comment]
What would the expected functionality be if we used the `url` param in the editor? Im guessing that it would open this in a `Viewer` mode rather than the `Editor` mode, right? I have not actually tested using the `url` param when we had implemented #478, so we will need to be sure those two features work as intended.

**Comment by kylelaker** [comment]
> What would the expected functionality be if we used the `url` param in the editor

It should be ignored. So I guess testing this in the end-to-end tests may actually be kinda challenging...
