### ISSUE TITLE
OSCAL Leveraging SSP's load in Viewer with warnings

### ISSUE THREAD

**Issue by tuckerzp** [EasyDynamics/oscal-react-library#572]
### Description

When loading some of the `SSP` examples leveraging OSCAL in https://github.com/usnistgov/oscal-content/tree/main/examples/ssp/json, the `Viewer` loads with warnings. 

### Steps to Reproduce

1. Load the `Viewer`
2. Load one of the following `SSPs`.
   - https://raw.githubusercontent.com/usnistgov/oscal-content/main/examples/ssp/json/oscal_leveraged-example_ssp-min.json
   - https://raw.githubusercontent.com/usnistgov/oscal-content/main/examples/ssp/json/oscal_leveraging-example_ssp.json
3. Open up console to view warnings

### Expected behavior

`SSP` is displayed without console warnings. 

### Actual Behavior

Console contains warnings like the following occur
 
Loaded with https://raw.githubusercontent.com/usnistgov/oscal-content/main/examples/ssp/json/oscal_leveraging-example_ssp.json

```
Warning: Each child in a list should have a unique "key" prop.

Warning: Failed prop type: The prop `title` is marked as required in `ForwardRef(Tooltip)`, but its value is `undefined`.
```

**Comment by kylelaker** [comment]
To be very clear, the outcome of this **may not be changes in _our_ code base**. We need to validate that we are setting `key`s that the _specification_ says should be unique. Generally, this would be the `uuid` (though, to be clear, not necessarily `component-uuid`).

So _before_ any changes are made, we need an analysis of where we're non-compliant with the specification or where/if the examples are non-compliant. If it's the former, we should fix our code. If its the latter, we should submit a patch upstream.

I am okay with _degraded_ behavior in the application (slightly incorrect appearance or console warnings) when a document isn't compliant with the specification in subtle ways; but we do want to make sure that we are compliant with the spec.

**Comment by brian-easyd** [comment]
@tuckerzp to revisit and either refine, rework, or withdraw.
