### ISSUE TITLE
Begin to Support TypeScript

### ISSUE THREAD

**Issue by tuckerzp** [EasyDynamics/oscal-react-library#596]
### Description

As a developer, I want to better ensure that variables being used are of the correct type before running any code. 

The use of stricter type checking through TypeScript would help better ensure quality code without needing to run it. This would greatly increase the speed of which code can be written and make maintaining code in the future a lot less tedious. 

Ideally we will have all of our components written in TypeScript eventually. Having the ability to make files created in the future be `.ts` will be enough for this initial increment. 

### Acceptance Criteria

- [ ] TypeScript is a dependency in the application
- [ ] A few of our current files are rewritten in TypeScript

### Proposed Solution

#493 is a really good start for this issue. We already have a few of our files rewritten in TypeScript. However the changes made have caused linting failure and regression of some functionality. 

### Additional Notes

When rewriting things in TypeScript we want to avoid the use of `any` as much as possible.

### Implementation

- [X] I can (or plan to) submit a pull request to implement this
- [ ] Implementing this may result in a breaking change

**Comment by kylelaker** [comment]
Before we really start to make much progress or do any work here, we need types for the OSCAL objects we're operating on. Until that happens, I am going to mark this story as blocked.

**Comment by kylelaker** [comment]
I am going to removed the "blocked" label. There are some things we can try to get basic typing at least (and we can just ignore stuff in `.js` files for now).
