### ISSUE TITLE
Withdrawn "top-level" controls are no longer identifiable

### ISSUE THREAD

**Issue by kylelaker** [EasyDynamics/oscal-react-library#635]
### Description

Previously, withdrawn controls in SP 800-53r5 were shown with a strikethrough (or maybe it was just lighter text?). After #602, they are no longer shown that way.

This impacts controls like AC-15 but not others, like AC-2.10.

### Environment

https://oscal-viewer.msd.easydynamics.com/

### Steps to Reproduce

1. Open https://oscal-viewer.msd.easydynamics.com/catalog?url=https://raw.githubusercontent.com/EasyDynamics/oscal-demo-content/main/catalogs/NIST_SP-800-53_rev5_catalog.json
2. View a control that was been withdrawn in Rev 5 (AC-15)

### Expected behavior

The item should not expand if there isn't any text. Withdrawn controls should have a unique appearance indicating their status.

### Actual Behavior

The title is shown and it expands; however there is neither any text or indication that it has been withdrawn

### Additional Notes

_Note_: I am not sure whether `{ "name": "status", "value": "withdrawn" }` is part of the specification or just a convention; on https://pages.nist.gov/OSCAL/reference/latest/catalog/json-reference/#/catalog/controls/props the only defined `name` is `marking` and I do not see any definitions for status at https://github.com/search?q=repo%3Ausnistgov%2FOSCAL%20withdrawn&type=code

**Comment by brian-easyd** [comment]
@brian-easyd to weigh in on the relationship between withdrawn controls and the OSCAL spec.
