### ISSUE TITLE
Revamp `Appbar` UI/UX

### ISSUE THREAD

**Issue by Bronstrom** [EasyDynamics/oscal-react-library#648]
Several elements currently in `Appbar` should be adjusted or removed.

Separation of application name (title) and "page"/model could be more meaningful. The title for "OSCAL Viewer/Editor" (with EasyDynamics positioned near it) should be placed left in the `AppBar`, while the model type should be placed in the center to highlight what type of model the user is viewing. This will help the user understand the scope of the tool, which currently seems more ambiguous due to these being mashed together.

![Appbar_Title_Page_Seperation](https://user-images.githubusercontent.com/35196021/213815023-40185edd-4a9a-4d03-b5b1-f7a78933bbb5.png)

The GitHub link should be removed from `AppBar` and placed somewhere else, ideally the vertical side menu.

In most of the Easy Dynamics company applications, the company logo is often place right next to the title of the application. This may be something implemented in a future logo/icon overhaul, although "Powered by Easy Dynamics" should be more closely associated with the title of the application. Below are two approaches to how we can show this:

Approach 1:

This approach is quite common to how the company branded applications appear. Depending on the approach taken with reworking "REST Mode" this may not look as clean.

![Title_Logo_Option1](https://user-images.githubusercontent.com/35196021/213815340-d44c5900-59be-4c55-8083-3633fe7aca4d.png)

Approach 2:

This approach may be easiest by taking these two text elements and turning them into a vector image. This may also be able to be achieved with a table containing two rows.

![Title_Logo_Option2](https://user-images.githubusercontent.com/35196021/213815410-a7c76232-5c2f-4b0e-bd2a-afa6e0bc5425.png)

Lastly, `Appbar` should have the "sticky" position. With the bar being locked to the top of the page, the user will have easy access to navigation no matter where they are on the page. `AppBar` is also relatively thin, so it probably won't interfere with the user interacting with the Viewer/Editor with it being on screen at all times.

**Comment by kylelaker** [comment]
@Bronstrom what is the status of this?

**Comment by Bronstrom** [comment]
I believe UX navigation changes will be redesigned/supported by @emcathow in the future

**Comment by Bronstrom** [comment]
Capturing the Drawer component and vertical menu in a more concrete issue: https://github.com/EasyDynamics/oscal-react-library/issues/885. The design has also been decided in mock-ups.
