### ISSUE TITLE
Support viewing base64-encoded data

### ISSUE THREAD

**Issue by laurelmay** [EasyDynamics/oscal-react-library#671]
### Description

As a document author, I want to view the rendered version of base64-encoded data in the OSCAL Viewer.

#### Context

OSCAL [supports](https://pages.nist.gov/OSCAL/reference/datatypes/#base64binary) representing images and other media as base64-encoded strings. This is generally wrapped in a [base64 object](https://pages.nist.gov/OSCAL/reference/latest/catalog/json-reference/#/catalog/back-matter/resources/base64). Both an `rlink` and `base64` may be specified, in which case they are supposed to refer to the same content.

OSCAL supports omitting the media type for `base64` objects as well. In general, when the media type is omitted, browsers will treat this as ASCII-encoded plain text[^1] in compliance with [RFC-2397](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs). This is _unlikely_ to be the intended encoding of most referenced documents.

[^1]: For example, Mozilla's compliance is documented at https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs 

### Acceptance Criteria

- base64-encoded images can be viewed in the web viewer
- when a `media-type` is not specified, we _do not_ make an attempt to render the document (OSCAL does not give guidance on a default `media-type` type value)
- an `rlink` to a valid URL is _always_ preferred over equivalent base64-encoded data

### Proposed Solution

We want to take care to avoid naive string-concatenation to build the `data:`-scheme URLs required for this; it will be important to properly URL encode/decode the data and we should make use of browsers' APIs for this.

For images, the `srcset` attribute _may_ be useful here but this may also be an inappropriate use of that attribute (so review documentation before pursuing that implementation).

### Implementation

- [ ] I can (or plan to) submit a pull request to implement this
- [ ] Implementing this may result in a breaking change

**Comment by brian-easyd** [comment]
Will only "display" image types that we can reasonably expect modern browsers to support.

**Comment by tuckerzp** [comment]
@kylelaker I could use some help on the best solution to handling this problem. We have made a few assumptions that make this kind of a nasty problem to fix. I _think_ I have a decent solution, but also thought I may be missing something. 

### Background

#### `base64` vs `rlink` in json

```
{
  rlinks [0 or 1]: [
    {
      href [1],
      media-type [0 or 1],
      hashes [0 or 1]
    }
  ],
  base64 [0 or 1]: {
    filename [0 or 1],
    media-type [0 or 1],
    value [0 or 1]
  }
}
```

#### `OSCALDiagram`:

This is the only place that I know of we would want to display `base64`, so I began there. The most annoying part of this component is:

https://github.com/EasyDynamics/oscal-react-library/blob/a0c5b1f29ddb538793f8bc2383092f7f8660565b/src/components/OSCALDiagram.js#L13-L23

Things to note:

- `resolveLinkHref` is being called as all we currently have is a `uuid` & a list of `backMatter`. 

#### `resolveLinkHref` (Where I think the issues begin)

https://github.com/EasyDynamics/oscal-react-library/blob/a0c5b1f29ddb538793f8bc2383092f7f8660565b/src/components/oscal-utils/OSCALLinkUtils.js#L15-L27

Things to note:

- `getAbsoluteUrl`: We always assume resolving a link href will result in a url. **I think this is the biggest issue here**.
- `getUriFromBackMatterByHref().href`: Another assumption that the only thing we would resolve from backmatter would be a `uri` or `url`.

#### `getUriFromBackMatterByHref`

This is where I initially focused on fixing things. It _seems_ like it would be the problem. I think it makes a few assumptions that aren't fantasic, but overall it does what it says it does: gets a uri from back matter by href. 

https://github.com/EasyDynamics/oscal-react-library/blob/a0c5b1f29ddb538793f8bc2383092f7f8660565b/src/components/oscal-utils/OSCALBackMatterUtils.js#L21-L41

Things to note:

- Having this function return the base64 value as the `image src` **does not fix issue**. Our friend above attempts to get a `href` and everything breaks. I don't think it makes sense to be returning a `uri` if we are trying to deal with `base64`.

### Proposed solution

Create a middle function between `resolveLinkHref` & `getUriFromBackMatterByHref`

```Javascript
function getBackMatterItemByHref() {
   const item;   

   if (item.type == rlink) 
      return getUriFromBackMatterByHref;
   }
   
   if (item.type == base64)
      return item.value;
   }
}
```

This would also require some changes in `resolveLinkHref`, which is not super flexible currently. This seems like a clean way to keep the functions true to their meaning and would require very little refactoring.

**Comment by kylelaker** [comment]
@tuckerzp Great question and thanks for bringing this up! I _definitely_ think you're on the right track; however, it's not quite going to support us long-term. We know that in the future, we don't want to have to pass around all these massive objects all the time (and back matter is big) but it is where we need to be today. With that, I am wondering if we should take an approach like the following (assume all types are their OSCAL types or the TS builtins unless otherwise defined):

```ts
interface ResolvedUri {
  /**
   * The URI for the resource.
   * 
   * This may not be an HTTP(S) URL; it may be a data URI with base64-encoded
   * data.
   */
  readonly uri: string;

  /**
   * The media type for the resource, if known.
   */
  readonly mediaType?: string;
}


interface ResourceLinkQuery {
  /**
   * Get a URI for a resource based on its URI reference.
   * 
   * @param uri - the URI reference to lookup
   * @param mediaType - the preferred media ty
   */
  resolve: (uri: string, mediaType?: string) => ResolvedUri | undefined;
}

class BackMatterLookup implements ResourceLinkQuery {
  // the `preferBase64` parameter would allow operating "offline" without access to
  // public resources
  constructor(private readonly backMatter: BackMatter, private readonly preferBase64?: boolean);

  private resolveUuid(uuid: string, mediaType?: string): ResolvedUri | undefined {
    const resource = backMatter.resources.find((resource) => resource.uuid === uuid);

    if (!this.preferBase64) {
      const rlink = resource?.rlinks?.find((rlink) => {
        const rlinkMediaType = rlink["media-type"];
        if (!mediaType || !rlinkMediaType) { return true; }
        return rlinkMediaType === mediaType;
      });
      if (rlink) {
        return { uri: rlink.href, mediaType: rlink["media-type"] };
      }
    }
    const base64 = resource?.base64;
    // We require media type to be present. In most cases in existing OSCAL documents,
    // media type is missing; however, the underlying document is not actually plain-text
    // data. If we don't specify a media type in the URI, the browser will assume that it
    // is plain text. This will cause a whole mess that we'd really rather avoid.
    // In the future, this may throw an error.
    if (!base64?.["media-type"]) {
      console.error(`Resource ${uuid} does not have a media-type specified`);
      return undefined;
    }
    if (!base64?.value) {
      console.error(`Resource ${uuid} does not have a value, so a URL cannot be constructed`);
      return undefined;
    }
    return {
      uri: `data:${base64["media-type"]};base64,${base64.value.replace("\n", "")}`,
      mediaType: base64["media-type"],
    }; 
  }

  private handleFullUri(uri: string): ResolvedUri | undefined {
    // I didn't actually think through this implementation. More work may be
    // required here.
    return { uri, mediaType: undefined };
  }

  override resolve(uri: string, mediaType?: string): ResolvedUri | undefined {
    if (!uri.startsWith("#")) {
      return resolveUuid(uri.slice(1), mediaType);
    }

    return { uri, mediaType: undefined };
  }
}
```

This means that in the future, we can write:

```ts
class ApiLookup implements ResourceLinkQuery {

  private readonly apiBaseUrl: string;
  private readonly documentPath: string

  constructor(apiBaseUrl: string) {
    this.apiBaseUrl = apiBaseUrl;
  }

  override resolve(uri: string) {
    // 1. Make API call to get the base64 string, or a URL on the server for the data
    // 2. Return that data to the caller
  }
}
```

You could also envision (and this would probably be more correct) that the `preferBase64` would actually be its _own_ implementation of `ResourceLinkQuery`, something like `BackMatterLookupOnlyBase64` or some better name.

Callers would then do something like:

```ts
const queryThing = backMatter ? new BackMatterLookup(backMatter) : useApi ? new ApiLookup(apiUri) : undefined;
return queryThing.resolve(uriReference);
```

Be aware: I wrote all this directly in GitHub. So it'd be a miracle for it to even be syntactically correct, let alone work as-is and pass the linter.
