### ISSUE TITLE
Support editing basic back matter resource data

### ISSUE THREAD

**Issue by kylelaker** [EasyDynamics/oscal-react-library#687]
### Description

As a catalog author, I want to edit the title, description, and other basic metadata of back matter resources

### Acceptance Criteria

- `title` (`markup-line`) and `description` (`markup-multiline`) fields are properly displayed within the library (this should already be completed but let's fix-up any issues and avoid regressions)
- `title` and `description` fields for back matter resources can be edited and saved within the library
- When saved, changes to the `title` and `description` field are sent to the REST API following the [specification](https://editor.swagger.io/?url=https://raw.githubusercontent.com/EasyDynamics/oscal-rest/develop/openapi.yaml) using the best available method

### Proposed Solution

It is likely best to either (a) add new routes to the API specification to support back matter editing; or (b) use the `PATCH /{documentType}/{id}` routes

### Implementation

- [ ] I can (or plan to) submit a pull request to implement this
- [ ] Implementing this may result in a breaking change

**Comment by brian-easyd** [comment]
Builds on Issue #710 - may want to have the same person work both.

**Comment by tuckerzp** [comment]
### Status Update:

It is unlikely the task will be finished by demo tomorrow morning. 

My initial thought was that it would be trivial enough to add a rest path to handle back matter resources. I spent more time than I intended trying to get that to work. We have made a few assumptions that did not turn out to be true there. Namely that all OSCAL objects, including system implementation requirements, are root level documents. Trying to make resources work with that proved to be more difficult than I thought.

Currently I am working on just using a document level rest call to update resources. This too is proving to need more work than I imagined and there is some refactoring involved to make things work. It should be doable, but will take longer than the time between standup and demo tomorrow.

**Comment by Bronstrom** [comment]
4/7/23 Sprint Planning - Moved from Sprint 44 to Sprint 45
