### ISSUE TITLE
Support viewing metadata locations

### ISSUE THREAD

**Issue by Bronstrom** [EasyDynamics/oscal-react-library#697]
### Description

As a catalog author, I want to view locations in regard to metadata.

### Acceptance Criteria

* The `location`s field and it's respective metadata is properly displayed within the React library. A `location`s metadata include:
   * `uuid` (not displayed to author)
   * `title` [1]
   * `address` [1]
   * `email-address` [0 to many)
   * `telephone-number` [0 to many)
   * `url` [0 to many)
   * `prop` [0 to many)
   * `link` [0 to many)
   * `remarks` [0 to many)

### Additional Notes

A lot of this should already be support. Some of a location's metadata like `link` and `remarks` are not currently supported.

### Implementation

- [ ] I can (or plan to) submit a pull request to implement this
- [ ] Implementing this may result in a breaking change

**Comment by tuckerzp** [comment]
@EasyDynamics/oscal-editor-reviewers 

## Proposed Design

### Background

Currently the `metadata` section holds a lot of information (see below). The `parties` and `roles` are both dealt with using [mui cards](https://mui.com/material-ui/react-card/) stored inside esentailly a styled `Grid`.

https://github.com/EasyDynamics/oscal-react-library/blob/a206c9e69ba45784fef9ec1ccfdc792a595d90cb/src/components/OSCALMetadata.js#L59 

They both have a details button that allows the user to get more information beyond like a basic title. For the most part these are fairly similar parts (highlighted by the poor name choice of the styled `Grid` above ). There is definitely some room to make those things a bit more generic. 

![image](https://user-images.githubusercontent.com/39490074/225416366-acd3af8b-1c8b-4bb8-b773-5016fd7425e9.png)

### Design

I think the card design we have currently for `parties` and `roles` works pretty well. It gives the minimum amount of data needed to be useful and allows for the user to click to get more information. I also think that `locations` can be solved using similar `Card` components. I think having extra information appear in a `Dialog` also makes the component a lot more flexible to add or change things. 

If we do use `Card` components, we will need to avoid the page getting too cluttered. I think making the outer `Grid` for `parties`, `roles`, & `locations` [collapsible](https://mui.com/material-ui/api/collapse/) will help clean up the `Metadata` a lot. I also think it is unlikely that a user will _always_ want to see all the information in `Metadata`. 

Essentially each section will be collapsible and upon opening will show a list of cards. Kinda like how we display control groups today. I am hoping this will clean up `Metadata` a bit to be more generic and flexible to add onto in the future as well.

**Comment by brian-easyd** [comment]
As discussed at the end of today's stand-up, there should be one code base for displaying location information that can then be referenced for different uses such as:
- a modal wrapper for displaying location data as a modal
- an in-line wrapper for displaying location data directly on a page
- no wrapper for incorporating location data into a larger data construct, such as when a party is linked to a location and we wish to display the location information co-mingled with the party information
