### ISSUE TITLE
Support viewing the metadata keywords property

### ISSUE THREAD

**Issue by Bronstrom** [EasyDynamics/oscal-react-library#707]
### Description

As a catalog author, I want to view the keywords property in regard to metadata.

### Acceptance Criteria

* The `prop[@name='keyword']` field are properly displayed within the React library

### Additional Notes

- See https://pages.nist.gov/OSCAL/reference/latest/complete/json-reference/#/profile/metadata

### Implementation

- [ ] I can (or plan to) submit a pull request to implement this
- [ ] Implementing this may result in a breaking change

**Comment by brian-easyd** [comment]
![image](https://user-images.githubusercontent.com/106116211/223468561-0a2cedfa-3edd-4c03-9e22-df29eb5ad89c.png)

**Comment by brian-easyd** [comment]
@Bronstrom to create a separate ticket on generic displaying of properties for any assembly.

@brian-easyd to create a ticket for handling of the metadata/marking property.

**Comment by emcathow** [comment]
I think the placement is solid, I would just flag that we want to make sure we don't suggest interactivity when there isn't any 

IE the use of color/ pill shape may suggest a user could click on the keywords

**Comment by kylelaker** [comment]
If we use the Chips, we want to probably keep them relatively small. We can envision that editing eventually will allow having an "X" or a trash can icon on them.

We should probably use a slightly smaller text size than regular body font. I do think that using color will make them a little more fun; we could use the same algorithm that we do for avatars. But users may get annoyed if they can't set the color.
