### ISSUE TITLE
Conform JSDoc `@param` and `@returns`

### ISSUE THREAD

**Issue by Bronstrom** [EasyDynamics/oscal-react-library#724]
### Description

As a developer of the OSCAL Viewer/Editor, I would like to see `@param` and `@returns` JSDoc to follow a common code practice specific to the TypeScript spec.

### Acceptance Criteria

- All `@param`s are revised to follow the code practice below:
   - `@param {<type>} <variable-name> <description>`
   - ex: `@param {string} url A given href`
- All `@returns` are revised to follow the code practice below:
   - `@returns {<type>} <description>`
   - ex: `@param {string} A valid or blank extension type`

### Additional Notes

See the following TypeScript code standards for more information: https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#param-and-returns

### Implementation

- [ ] I can (or plan to) submit a pull request to implement this
- [ ] Implementing this may result in a breaking change

**Comment by kylelaker** [comment]
I do not think that we can meaningfully do this in a single ticket. I think this is an iterative improvement as we go forward and touch these files/docs, not something we set aside and just update docs for a whole sprint. They are clear _enough_ as-is. Instead, I would like to see us document development standards that we use JSDoc (and for reviewers to enforce that) for any exported functions.

@Bronstrom if you'd like, you may create that task to do the development standards update!
