### ISSUE TITLE
Prose is not displayed for groups in a catalog

### ISSUE THREAD

**Issue by kylelaker** [EasyDynamics/oscal-react-library#742]
### Description

Groups can have `parts` which have `prose`. This prose is not currently displayed in the viewer application but it should be, perhaps above the controls on the right-hand side of the tab selector?

### Environment

oscal-viewer.msd.easydynamics.com

### Steps to Reproduce

*Sample catalog link will be provided*

### Expected behavior

The prose for a group should be displayed, both for `/groups` and `//groups`.

### Actual Behavior

No prose is displayed for groups. In fact, it seems like `parts` is never considered at all.

**Comment by brian-easyd** [comment]
Consider using this sample catalog for testing:
https://github.com/EasyDynamics/oscal-demo-content/blob/test-content/catalogs/basic-test-catalog.json
