### ISSUE TITLE
Update SSP and Component Definition to Display Profile Modifications

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#75]
As user of the OSCAL Viewer or another app consuming the OSCAL React components, I want to be able to see the profile control modifications in the SSP’s implemented requirements and Component Definition’s control implementations so that I can fully understand the compliance requirements and how an SSP or Component Definition satisfies them.

### Acceptance Criteria
* The Component Definition view displays the control modifications from imported profiles
  * The example component definition [brings in the FedRAMP High profile](https://github.com/usnistgov/oscal-content/blob/master/examples/component-definition/json/example-component.json#L46) so should display that profile's AC-2.3 constraints and additions for that particular control implementation
* The SSP view displays the control modifications from imported profiles
  * The example SSP brings in the [800-53 rev4 Moderate profile](https://github.com/usnistgov/oscal-content/blob/master/examples/ssp/json/ssp-example.json#L44) so should display that profile's AU-1 additions.
* The same acceptance criteria from #74 will apply here

### Implementation Notes
* We should be able to leverage the work/components previously created for the Profile VIew

### Child Issues
- [x] Display Modifications in SSP 
- [x] Display Modifications in Component Definition

**Comment by tuckerzp** [comment]
@rgauss or anyone else from the sprint planning meeting, we talked about there being a component that `profile`, `ssp`, & `component definition` have in common that would display modifications. Does anyone know what component that is? 

Another issue that I am having is that `profile` has a nice `modify` attribute, for listing modifications, whereas `ssp` & `component definition` do not have something similar. Is there another way to get those modifications?

**Comment by Bronstrom** [comment]
@tuckerzp I'm not entirely sure about the first question. 

To answer the second: From my understanding, a `profile` is imported from the `ssp` & `component definition`, providing the modifications.

**Comment by tuckerzp** [comment]
> a `profile` is imported from the `ssp` & `component definition`, providing the modifications.

That is what I thought as well, but `component definition`  from the example https://github.com/usnistgov/oscal-content/blob/master/examples/component-definition/json/example-component.json#L46 does not have an `import-profile` attribute. At least when I log it's `oscalData` from the `OSCALLoader`.

**Comment by rgauss** [comment]
> Does anyone know what component that is?

`OSCALControlPart` should be one?

**Comment by rgauss** [comment]
> > a `profile` is imported from the `ssp` & `component definition`, providing the modifications.
> 
> That is what I thought as well, but `component definition` from the example https://github.com/usnistgov/oscal-content/blob/master/examples/component-definition/json/example-component.json#L46 does not have an `import-profile` attribute. At least when I log it's `oscalData` from the `OSCALLoader`.

The component definition uses the `source` properties you've pointed at.  The modifications of that source (if it is a profile) need to be sent to the controls rendering.
