### ISSUE TITLE
Locale Formatted Timestamps

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#76]
As a user involved in the governance, risk, and compliance of systems and components, I want to **any** date/time timestamps current displayed that are strongly typed in the OSCAL model to be presented in the proper locale format  so that I can more easily interpret their values.

### Acceptance Criteria
* All date/time timestamps that are specified as such in the OSCAL data model are locale formatted
  * A default locale of EN/US would be sufficient for this iteration, future implementations may grab the locale configured in the browser.

**Comment by rgauss** [comment]
Something like [moment.js](https://momentjs.com/) might work here.

**Comment by tuckerzp** [comment]
@rgauss Are there places other than OSCALMetadata that strongly typed dates occur? Looking through the examples we have, that is the only place I see it occur.
