### ISSUE TITLE
Display Control Modifications According to Position Value

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#82]
As a user of the OSCAL viewer or underlying React components, I want to see the indicator of modifications displayed in a way that reflects the [position value](https://pages.nist.gov/OSCAL/reference/latest/profile/json-reference/#/profile/modify/alters/adds/position) that has been defined for them so that I can understand how they apply to the control.

### Acceptance Criteria
* The visual indicator of modifications is displayed in a position relative to the control or `id-ref` that reflects the defined position value for that modification

**Comment by brian-easyd** [comment]
It sounds like of the four possibilities, we are only accomplishing "after" at this point and need to accomplish the other three.
- **before**: Preceding the id-ref target
- **after**: Following the id-ref target
- **starting**: Inside the control or id-ref target, at the start
- **ending**: Inside the control or id-ref target, at the end
