### ISSUE TITLE
OSCAL namespace URI

### ISSUE THREAD

**Issue by jon-burns** [EasyDynamics/oscal-react-library#862]
According to the [OSCAL 1.0.5 reference](https://pages.nist.gov/OSCAL/reference/1.0.5/catalog/json-reference/), the NIST OSCAL namespace URI is defined using HTTP rather than HTTPS, i.e.,
- http://csrc.nist.gov/ns/oscal

Here is the relevant line of code:
https://github.com/EasyDynamics/oscal-react-library/blob/d91b7d087b37504c0481b923bd20032c54af2790/packages/oscal-react-library/src/components/oscal-utils/OSCALPropUtils.ts#L7

**Comment by kylelaker** [comment]
@jon-burns Thank you so much for reporting this! That is definitely an unfortunate error and #863 will correct it and add a test to avoid future regressions. Further, I am going to make sure we re-evaluate our corpus of larger testing documents to make sure we include both documents with and without the namespace specified (and generally similar types of checks).

**Comment by kylelaker** [comment]
Additionally, would you be willing to write a note either on this issue or to oscal@easydynamics.com with an overview of how you're using the tool/library? We're going through a process of making technical improvements and adding new features and want to make sure we consider the community's needs while doing so.
