### ISSUE TITLE
Improved Catalog Control Group Navigation

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#88]
As a user involved in the governance, risk, and compliance of systems and components, I want to be able to easily navigate different control groups and the controls within them in a catalog so that I can quickly get to and understand the details of those controls.

### Acceptance Criteria
- [x] The control groups in a catalog can be accessed in a left-hand navigation index
- [x] Clicking on a control group displays that group's controls
- [x] Individual controls are displayed in collapsible panel, initially closed

### Implementation Notes
* The [`Drawer Component`](https://mui.com/material-ui/react-drawer/#persistent-drawer) may be a good solution to displaying the navigation. We will need to make sure the naming is distinct to the what is currently called `DrawerSelector`.

Mockup:
![catalog-v2-initial](https://user-images.githubusercontent.com/168671/124276808-49dc4a00-db12-11eb-9570-5b039f0bb92d.jpg)

**Comment by tuckerzp** [comment]
To clarify a question I originally had, this must be done before https://github.com/EasyDynamics/oscal-react-library/issues/176. Our initial implementation will display a control group's controls by using the state. We will later on use anchor links to clean this up a bit in the future issue.
