### ISSUE TITLE
Update navigation menus

### ISSUE THREAD

**Issue by Bronstrom** [EasyDynamics/oscal-react-library#885]
### Description

As a consumer of the Editor, I would like to view a visual of how the navigation will appear.

### Acceptance Criteria

* In the Editor, an `AppBar` appears at the top of the window, including:
  * A search bar
  * An `Avatar` for the user and place for the user's name
  * Notification and Settings buttons
* In the Editor, a Permanent Drawer component displays on the left side of the window, including:
  * The company logo in the top left corner
  * A hierarchical navigation tab menu
  * "Logout" and "Support" tabs

### Proposed Solution

The implementation should fall in line with the style guide and mock-ups made for the tool.

### Additional Notes

This implementation does not need link/routing support and should be purely handled on the front-end.

### Implementation

- [ ] I can (or plan to) submit a pull request to implement this
- [ ] Implementing this may result in a breaking change

**Comment by Bronstrom** [comment]
Capturing the Drawer component and vertical menu in a more concrete issue: https://github.com/EasyDynamics/oscal-react-library/issues/885. The design has also been decided in mock-ups.

**Comment by brian-easyd** [comment]
@Bronstrom the mock-ups are for the editor. We have not considered changes to the viewer in our UI design work. Please revise this to be about the editor.

**Comment by Bronstrom** [comment]
Sounds good, will swap out the word "Viewer" for "Editor" in the issue description.

**Comment by Bronstrom** [comment]
6/22/23 Sprint Planning - Moved from Sprint 49 to Sprint 50

**Comment by Bronstrom** [comment]
7/6/23 Sprint Planning - Moved from Sprint 50 to Sprint 51

**Comment by Bronstrom** [comment]
We decided to add a dev flag to the application to toggle development features on and off, which currently is just the navigation menus in this issue. In order to view this feature, the Editor must be running with `isDevMode` set to `true` in `packages/oscal-viewer/src/App.js`.
