### ISSUE TITLE
Display Existing Catalogs and Baselines (Profiles)

### ISSUE THREAD

**Issue by brian-easyd** [EasyDynamics/oscal-react-library#887]
### Description

As a security practitioner, I want to see a list of all OSCAL-based catalogs and baselines (profiles) within the system and be able to select one for viewing/editing.

The list should include the following for each OSCAL catalog or profile within the system:
- Title
- Last Modified
- Document Version
- Publication Date

Each item should also offer the ability to open the catalog or profile. 
The detail of what happens when a catalog or profile is open is outside the scope of this issue. 

### Acceptance Criteria

- Aligned with the Spring 2023 styling strategy, guidance, and standards
- The user is able to indicate they wish to see a list of catalogs and baselines
- A list of all available catalogs and baselines is presented to the user
- The list includes:
  - Title
  - Last Modified
  - Document Version
  - Publication Date

### Proposed Solution

- A transaction may need to be defined on the back-end to support this call. 
- Perform an a Transaction API call to query for the list
- Format and present the list to users

### Additional Notes

See the screen mockup and UI developer's notes in [Figma](https://www.figma.com/file/ntIfIHIhMYbiqS9Nuc7EQG/Catalog-Mockups?type=design&node-id=8-1329&t=x5GqLMfITPmAInmo-0)

### Implementation

- [ ] I can (or plan to) submit a pull request to implement this
- [ ] Implementing this may result in a breaking change

**Comment by Bronstrom** [comment]
6/22/23 Sprint Planning - Moved from Sprint 49 to Sprint 50

**Comment by Bronstrom** [comment]
7/6/23 Sprint Planning - Moved from Sprint 50 to Sprint 51
