### ISSUE TITLE
Upload OSCAL Files

### ISSUE THREAD

**Issue by brian-easyd** [EasyDynamics/oscal-react-library#888]
### Description

As a security practitioner I want to upload existing OSCAL files into the tool so I can view and edit them.

The upload capability needs to send the file to the back end for validation and placement into the datastore.

The user interface should offer both a drag-and-drop capability as well as a file selection capability.

### Acceptance Criteria

- Aligned with the Spring 2023 styling strategy, guidance, and standards
- A valid OSCAL file is dropped into the drop zone, and ends up within the server's datastore in accordance with the datastore specification. 
- A valid OSCAL file is selected, and ends up within the server's datastore in accordance with the datastore specification. 
- An invalid OSCAL file is dropped into the drop zone and is rejected as invalid

### Proposed Solution

- file validation and placement into the datastore should be handled by the back end.
- An OTSL transaction and helper may be necessary 

### Implementation

- [ ] I can (or plan to) submit a pull request to implement this
- [ ] Implementing this may result in a breaking change

**Comment by emcathow** [comment]
No Catalogs/Baselines Uploaded: 
https://www.figma.com/file/ntIfIHIhMYbiqS9Nuc7EQG/Catalog-Mockups?type=design&node-id=8-977&t=iqrjELBQeVi4uCKQ-0 

Upload: 
https://www.figma.com/file/ntIfIHIhMYbiqS9Nuc7EQG/Catalog-Mockups?type=design&node-id=70-702&t=iqrjELBQeVi4uCKQ-0

Uploading: 
https://www.figma.com/file/ntIfIHIhMYbiqS9Nuc7EQG/Catalog-Mockups?type=design&node-id=70-703&t=iqrjELBQeVi4uCKQ-0

Success: 
https://www.figma.com/file/ntIfIHIhMYbiqS9Nuc7EQG/Catalog-Mockups?type=design&node-id=70-704&t=iqrjELBQeVi4uCKQ-0

Fail: 
https://www.figma.com/file/ntIfIHIhMYbiqS9Nuc7EQG/Catalog-Mockups?type=design&node-id=70-705&t=iqrjELBQeVi4uCKQ-0

**Comment by Bronstrom** [comment]
6/22/23 Sprint Planning - Moved from Sprint 49 to Sprint 50

**Comment by Bronstrom** [comment]
7/6/23 Sprint Planning - Moved from Sprint 50 to Sprint 51

**Comment by Bronstrom** [comment]
9/7/23 Sprint Planning - Moved from Sprint 54 to Sprint 55

**Comment by brian-easyd** [comment]
9/21/2023
- Need UPLOAD button need to go directly to upload screen
- Need error message functionality
- Brad to make styling pass
- Can't yet accept XML files (need back-end support)
Moving to next sprint

**Comment by Bronstrom** [comment]
9/21/23 Sprint Planning - Moved from Sprint 55 to Sprint 56

**Comment by brian-easyd** [comment]
2023-10-05 Review
- Fix error message (punctuation and capitalization)
- Clicking the X in error message only makes error message go away

**Comment by Bronstrom** [comment]
10/05/23 Sprint Planning - Moved from Sprint 56 to Sprint 57

**Comment by brian-easyd** [comment]
10/19/2023 - Closing based on functional completeness. Addressing styling alignment as part of #917
