### ISSUE TITLE
Manage Groups in Catalogs

### ISSUE THREAD

**Issue by brian-easyd** [EasyDynamics/oscal-react-library#889]
### Description

As a catalog author I want the ability to create, organize and remove groups within a catalog so that I can later organize controls within the groups.

Only empty groups (no controls, child groups, or parameters) may be deleted.

Any controls, child groups or parameters within the group move with the group.

### Acceptance Criteria

- Aligned with the Spring 2023 styling strategy, guidance, and standards
- create multiple group
- change the order of a group
- move a group from being a peer of another group to be the child of that group
- move a group from bring the child of another group to being a peer of that group
- on a level other than the top level, move a group from being a peer to being a parent
- close and re-open the catalog to show the persistence of the changes
- delete an empty group
- attempt to delete a non-empty group and demonstrate the function is not allowed

### Proposed Solution

Use transaction API calls. If necessary, build OTSL transaction(s) and helper function(s) to manipulate groups within the catalog.

### Additional Notes

For MVP we are changing the physical order of the groups within the file. Post MVP we will also work with the optional "sort-id" property.

### Implementation

- [ ] I can (or plan to) submit a pull request to implement this
- [ ] Implementing this may result in a breaking change

**Comment by brian-easyd** [comment]
Here are high fidelity mock-ups:
https://www.figma.com/file/ntIfIHIhMYbiqS9Nuc7EQG/Catalog-Mockups?type=design&node-id=52-980&t=SDzXVW6Sd1Gy9vt8-0

https://www.figma.com/file/ntIfIHIhMYbiqS9Nuc7EQG/Catalog-Mockups?type=design&node-id=52-1247&t=fRihCInDTTv9onzD-0

**Comment by Bronstrom** [comment]
6/22/23 Sprint Planning - Moved from Sprint 49 to Sprint 50

**Comment by Bronstrom** [comment]
7/6/23 Sprint Planning - Moved from Sprint 50 to Sprint 51

**Comment by brian-easyd** [comment]
Guidance on _Increase/Decrease Indent_ buttons now available here:
[https://github.com/EasyDynamics/oscal-react-library/wiki/General-Specifications](https://github.com/EasyDynamics/oscal-react-library/wiki/General-Specifications)

**Comment by brian-easyd** [comment]
For indent behavior, please see:
[https://github.com/EasyDynamics/oscal-react-library/wiki/Specification-%E2%80%90-Indent-States-and-Behaviors](https://github.com/EasyDynamics/oscal-react-library/wiki/Specification-%E2%80%90-Indent-States-and-Behaviors)

**Comment by brian-easyd** [comment]
2023-08-24 Moving to Sprint #54

**Comment by Bronstrom** [comment]
9/7/23 Sprint Planning - Moved from Sprint 54 to Sprint 55

**Comment by brian-easyd** [comment]
9/21/2023:
- Work with Jim to fix back-end delete functionality
- Brad to make final clean-up pass on styling
Moving into next sprint.

**Comment by Bronstrom** [comment]
9/21/23 Sprint Planning - Moved from Sprint 55 to Sprint 56
