### ISSUE TITLE
Display of Removed Control Elements in Profiles

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#89]
As a user involved in the governance, risk, and compliance of systems and components, I want to browse an OSCAL Profile in a user interface and see its removed control elements so that I can better understand the control modifications within it.

### Acceptance Criteria
* The Profile viewer shows the removal of control elements of an OSCAL Profile

### Implementation Notes
* This may require a deeper investigation of the current [Profile resolution guidance from NIST](https://pages.nist.gov/OSCAL/concepts/processing/profile-resolution/)
* Perhaps a simple strikethrough font variant of the control element removed would be a sufficient visual indicator

**Comment by Bronstrom** [comment]
This is modify/alter/remove.

**Comment by brian-easyd** [comment]
control-level exclude is addressed by EasyDynamics/oscal-react-library#91

**Comment by Bronstrom** [comment]
3/10/23 Sprint Planning - Moved from Sprint 42 to Sprint 43

**Comment by Bronstrom** [comment]
4/7/23 Sprint Planning - Moved from Sprint 44 to Sprint 45
