### ISSUE TITLE
Manage the Hierarchy of Controls

### ISSUE THREAD

**Issue by brian-comply0** [EasyDynamics/oscal-react-library#922]
### Description

As an OSCAL Catalog Creator, I want to manage the hierarchy of controls, so they are groups, sequenced, and have parent/child relationships that depict the relationship of controls.

### Acceptance Criteria

- Aligned with the Spring 2023 styling strategy, guidance, and standards
- change the order of controls
- move a control from one group to another (this includes moving controls between the root of the catalog and one of the catalog groups in either direction)
- move a control from being a peer of another control to be the child of that control
- move a group from bring the child of another control to being a peer of that control 
- close and re-open the catalog to show the persistence of the changes

### Implementation

- [ ] I can (or plan to) submit a pull request to implement this
- [ ] Implementing this may result in a breaking change

**Comment by brian-easyd** [comment]
Guidance on _Increase/Decrease Indent_ buttons now available here:
[https://github.com/EasyDynamics/oscal-react-library/wiki/General-Specifications](https://github.com/EasyDynamics/oscal-react-library/wiki/General-Specifications)

**Comment by brian-easyd** [comment]
For indent behavior, please see:
[https://github.com/EasyDynamics/oscal-react-library/wiki/Specification-%E2%80%90-Indent-States-and-Behaviors](https://github.com/EasyDynamics/oscal-react-library/wiki/Specification-%E2%80%90-Indent-States-and-Behaviors)

**Comment by Bronstrom** [comment]
9/7/23 Sprint Planning - Moved from Sprint 54 to Sprint 55

**Comment by Bronstrom** [comment]
9/21/23 Sprint Planning - Moved from Sprint 55 to Sprint 56

**Comment by brian-easyd** [comment]
2023-10-05 
    - children need natural order, not reverse order
    - drag and drop on controls needs ability to drop between controls, not just as child to a control
    - When creating new control:
        - Title not appearing
        - As soon as control label and title is saved, should move right to the edit control mode.

**Comment by Bronstrom** [comment]
10/05/23 Sprint Planning - Moved from Sprint 56 to Sprint 57

**Comment by brian-easyd** [comment]
10/19/203 Need to address disabling of increase/decrease indent consistent with this guidance:
[https://github.com/EasyDynamics/oscal-react-library/wiki/General-Specifications](https://github.com/EasyDynamics/oscal-react-library/wiki/General-Specifications)

Keeping open into next sprint.

**Comment by brian-easyd** [comment]
11/9/2023 - Design failed to address moving a control between groups. 
Emily and Brian to address in design, then Moustapha to implement. 
Moving issue to sprint 59.

**Comment by brian-easyd** [comment]
11/23/2023 - moving controls between groups hit snag on visualization. to work during next sprint.

**Comment by brian-comply0** [comment]
12/14/2023 This appears to fully satisfy the ticket. Moving to done!
