### ISSUE TITLE
Change the current CA certificate (Expires 5-19-24)

### ISSUE THREAD

**Issue by Bronstrom** [EasyDynamics/oscal-react-library#956]
Our current CA cert expires on 5-19-24. We will need to create a new one and swap it out before the current expires.

### Acceptance Criteria
- A new certificate is generated and replaced with the old one.

**Comment by brian-comply0** [comment]
@Bronstrom is this for the viewer or something else?

**Comment by Bronstrom** [comment]
@brian-comply0 This is actually for the Comply0 app. I think @jimstevensedc set our current certificate to expire 6 months after when he created it in November. We just will need to replace it before the date on this ticket

**Comment by Bronstrom** [comment]
Just talked to @jimstevensedc and understand now this certificate is specific to each developer's local environment. Jim has a script to automatically generate this key in `comply0-private`.

My bad - this key is based off of my own. Closing this issue.
